# Generated by Django 2.2 on 2020-02-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=5)),
                ('oc', models.BooleanField()),
                ('price', models.FloatField()),
                ('tag', models.CharField(choices=[('Core', 'C'), ('Speed', 'S'), ('Both', 'B')], max_length=5)),
                ('socket', models.CharField(choices=[('AM4', 'AM4'), ('1151', '1151'), ('2066', '2066'), ('TR4', 'TR4')], max_length=4)),
                ('cores', models.IntegerField()),
            ],
        ),
    ]
