# Generated by Django 2.2 on 2020-02-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_cpu_threads'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='igpu',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
