# Generated by Django 2.2 on 2020-02-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_cpu_igpu'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='speed',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
