# Generated by Django 2.2 on 2020-02-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_cpu_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='tdp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
