# Generated by Django 2.2 on 2020-02-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_disk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disk',
            name='brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='disk',
            name='rpm',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
