# Generated by Django 2.2 on 2020-02-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_gpu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='tag',
            field=models.CharField(choices=[('Thermals', 'Thermals'), ('Performance', 'Perf'), ('Price', 'Price')], max_length=11),
        ),
    ]
