# Generated by Django 2.2 on 2020-02-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20200209_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('type', models.CharField(default='DDR4', max_length=4)),
                ('modules', models.IntegerField()),
                ('price', models.FloatField()),
                ('frequency', models.IntegerField()),
                ('CAS', models.IntegerField()),
            ],
        ),
    ]
