# Generated by Django 2.2 on 2020-02-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_ram'),
    ]

    operations = [
        migrations.AddField(
            model_name='ram',
            name='model',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
