# Generated by Django 2.2 on 2020-02-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20200209_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('mbSize', models.CharField(choices=[('ATX', 'ATX'), ('m-ATX', 'm-ATX'), ('mini-ITX', 'mini-ITX')], max_length=8)),
                ('RGB', models.BooleanField()),
                ('window', models.BooleanField()),
                ('type', models.CharField(choices=[('Airflow', 'A'), ('Silence', 'S'), ('Normal', 'N')], max_length=7)),
            ],
        ),
    ]
