# Generated by Django 2.2 on 2020-02-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('watt', models.IntegerField()),
                ('certificate', models.CharField(choices=[('None', 'N'), ('Bronze', 'B'), ('Silver', 'S'), ('Gold', 'G'), ('Platinum', 'P'), ('Titanium', 'T')], max_length=8)),
                ('modular', models.CharField(choices=[('Full Modular', 'FM'), ('Semi Modular', 'SM'), ('Full Wired', 'FW')], max_length=12)),
            ],
        ),
    ]
