# Generated by Django 2.2 on 2020-02-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_psu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psu',
            name='certificate',
            field=models.CharField(choices=[('None', 'N'), ('80+', '80+'), ('Bronze', 'B'), ('Silver', 'S'), ('Gold', 'G'), ('Platinum', 'P'), ('Titanium', 'T')], max_length=8),
        ),
    ]
