# Generated by Django 2.2 on 2020-02-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_mb'),
    ]

    operations = [
        migrations.AddField(
            model_name='mb',
            name='memory_slots',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
