# Generated by Django 2.2 on 2020-02-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_auto_20200214_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tag',
            field=models.CharField(choices=[('Γενικές', 'Γενικές'), ('Ερωτήσεις επεξεργαστή', 'Ερωτήσεις επεξεργαστή'), ('Ερωτήσεις μητρικής', 'Ερωτήσεις μητρικής'), ('Ερωτήσεις ψύξης', 'Ερωτήσεις ψύξης'), ('Ερωτήσεις μνήμης', 'Ερωτήσεις μνήμης'), ('Ερωτήσεις κάρτας γραφικών', 'Ερωτήσεις κάρτας γραφικών'), ('Ερωτήσεις δίσκου', 'Ερωτήσεις δίσκου'), ('Ερωτήσεις τροφοδοτικού', 'Ερωτήσεις τροφοδοτικού'), ('Ερωτήσεις κουτιού', 'Ερωτήσεις κουτιού')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
